ALTER TABLE IF EXISTS rooms DROP COLUMN IF EXISTS closing_hour;
ALTER TABLE IF EXISTS rooms DROP COLUMN IF EXISTS opening_hour;
ALTER TABLE IF EXISTS rooms DROP COLUMN IF EXISTS operating_mode;
DROP TYPE IF EXISTS room_operating_mode;